[build]
    command = "npm install node-fetch"
    functions = "functions/"
    node_bundler = "esbuild"  # Ensures that dependencies like node-fetch are bundled

[build.environment]
    NODE_VERSION = "18" # Or another version compatible with node-fetch
